### ISSUE TITLE
ng2-uploader.com/demo doesn't upload

### ISSUE THREAD

**Issue by tomscript** [bleenco/ngx-uploader#107]
http://ng2-uploader.com/demo doesn't upload in Version 53.0.2785.116 (64-bit).

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
vendor.min.js:8 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map't.handleError @ vendor.min.js:8
vendor.min.js:8 ORIGINAL STACKTRACE:t.handleError @ vendor.min.js:8
vendor.min.js:8 Error: Uncaught (in promise): Error: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map'
    at p (vendor.min.js:6)
    at vendor.min.js:6
    at t.invoke (vendor.min.js:6)
    at Object.onInvoke (vendor.min.js:9)
    at t.invoke (vendor.min.js:6)
    at t.run (vendor.min.js:6)
    at vendor.min.js:6
    at t.invokeTask (vendor.min.js:7)
    at Object.onInvokeTask (vendor.min.js:9)
    at t.invokeTask (vendor.min.js:7)t.handleError @ vendor.min.js:8
vendor.min.js:6 Unhandled Promise rejection: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map' ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map'(…) Error: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map'
    at t.noMatchError (http://ng2-uploader.com/vendor.min.js:23:6072)
    at e.selector (http://ng2-uploader.com/vendor.min.js:23:5776)
    at e.error (http://ng2-uploader.com/vendor.min.js:22:29336)
    at e._error (http://ng2-uploader.com/vendor.min.js:9:13586)
    at e.error (http://ng2-uploader.com/vendor.min.js:9:13280)
    at e._error (http://ng2-uploader.com/vendor.min.js:9:13586)
    at e.error (http://ng2-uploader.com/vendor.min.js:9:13280)
    at e._error (http://ng2-uploader.com/vendor.min.js:9:13586)
    at e.error (http://ng2-uploader.com/vendor.min.js:9:13280)
    at e._error (http://ng2-uploader.com/vendor.min.js:9:13586)o @ vendor.min.js:6
vendor.min.js:6 Error: Uncaught (in promise): Error: Cannot match any routes: 'home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map'(…)o @ vendor.min.js:6
Failed to parse SourceMap: http://ng2-uploader.com/home/jan/www/demos/ng2-uploader-demo/dist/vendor.min.js.map
Failed to parse SourceMap: http://ng2-uploader.com/home/jan/www/demos/ng2-uploader-demo/dist/main.min.js.map
```

**Comment by jkuri** [comment]
Yeah I know, forgot to pay the uploading destination server :) need to fix that.
