### ISSUE TITLE
ng build --prod fails with error related to ngx-uploader 

### ISSUE THREAD

**Issue by katyasafford** [bleenco/ngx-uploader#456]
Hello guys,

I am trying to run `ng build --prod` command, and the build fails at about 92% with the following error:

```
ERROR in ./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts
Module build failed: Error: /Users/katya/Documents/Brinqa/brinqa-core/brinqa-app/src/main/client/node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/katya/Documents/Brinqa/brinqa-core/brinqa-app/src/main/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:740:23)
    at plugin.done.then (/Users/katya/Documents/Brinqa/brinqa-core/brinqa-app/src/main/client/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

Here is some information about my environment:
```
Angular CLI: 6.1.1
Node: 9.8.0
OS: darwin x64
Angular: 6.1.0
```

We use "ngx-uploader": "4.2.1"

Let me know if there's any additional information you might need. Thanks!

**Comment by jkuri** [comment]
Hi, update `ngx-uploader` version to latest which is `6.0.2` and it should work right off.

**Comment by katyasafford** [comment]
that worked! thank you!
