### ISSUE TITLE
Module build failed help me

### ISSUE THREAD

**Issue by sheep3724** [bleenco/ngx-uploader#461]
ERROR in ./node_modules/ng2-uploader/src/classes/index.ts
Module build failed: Error: C:\xampp\htdocs\NG\node_modules\ng2-uploader\src\classes\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/ng2-uploader/src/directives/ng-file-drop.ts
Module build failed: Error: C:\xampp\htdocs\NG\node_modules\ng2-uploader\src\directives\ng-file-drop.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/ng2-uploader/src/directives/ng-file-select.ts
Module build failed: Error: C:\xampp\htdocs\NG\node_modules\ng2-uploader\src\directives\ng-file-select.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/ng2-uploader/src/module/ng2-uploader.module.ts
Module build failed: Error: C:\xampp\htdocs\NG\node_modules\ng2-uploader\src\module\ng2-uploader.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/ng2-uploader/src/services/ng2-uploader.ts
Module build failed: Error: C:\xampp\htdocs\NG\node_modules\ng2-uploader\src\services\ng2-uploader.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (C:\xampp\htdocs\NG\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Sabdeth** [comment]
Your error says that you're having trouble installing 'ng2-uploader'. 
I think you're still referring to the old package name mentioned in the NPM website. 

Have you tried using the following command instead?
```npm install ngx-uploader --save```
